### ISSUE TITLE
Lib does not compile

### ISSUE THREAD

**Issue by equilDev** [chinoio/chino-ios#1]
I tried to install the lib(1.1) (iOS 13 & Xcode 11) with cocoaPods and got the following error:

![Bildschirmfoto 2019-09-24 um 11 29 53](https://user-images.githubusercontent.com/34444045/65499884-a4b52c00-debe-11e9-8a10-c9de6bf5e660.png)

**Comment by aarighi** [comment]
This repository has been migrated to gitlab.com/chinoio-public/sdk-chino-swift and will no longer be maintained on GitHub. Please reach out to tech-support@chino.io for any question, or if you wish to contribute to the SDK development.
